version: "3"
services:
  db:
    restart: always
    image: postgres:13-alpine
    ports:
      - "127.0.0.1:5435:5432"
    volumes:
      - data:/var/lib/postgresql/data
    env_file:
      - env.docker
  redis:
    restart: always
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis_data:/bitnami/redis/data
    ports:
      - "6379:6379"
  listener:
    build:
      context: .
      dockerfile: Dockerfile.listener
    env_file:
      - env.docker
    command: ["npm", "run", "listen"]
    ports:
      - "0.0.0.0:8080:8080"

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    env_file:
      - env.docker
    command: ["npm", "run", "start"]
    ports:
      - "3000:3000"

volumes:
  data:
  redis_data:
